spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuntieba?serverTimezone=UTC
    username: root
    password: root
    initial-size: 10
    max-active: 20
    max-wait: 15000
  data:
    redis:
      host: 192.168.23.128
      port: 6379
      password: 1234
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
          time-between-eviction-runs: 10s



mybatis-plus:
  type-aliases-package: com.fc.yuntieba.entity
  global-config:
    banner: false
  mapper-locations: classpath*:/mapper/*.xml



